version: "3"

services:
  api:
    container_name: api
    restart: always
    build:
      context: ./api
    ports:
      - "3333:3333"
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    env_file: ./api/.env   
  service-feed:
    container_name: service-feed
    restart: always
    build:
      context: ./service-feed
    ports:
      - "3335:3335"
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    env_file: ./service-feed/.env    
  service-mail:
    container_name: service-mail
    restart: always
    build:
      context: ./service-mail
    ports:
      - "3334:3334"
    links:
      - database
      - redis
    depends_on:
      - database
      - redis
    env_file: ./service-mail/.env   
  redis:
    container_name: redis
    restart: always
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - delivery-redis-db-data:/data
  database:
    container_name: mongo
    restart: always
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - delivery-mongo-db-data:/data/db
volumes:
  delivery-mongo-db-data:
  delivery-redis-db-data:
