version: "3"

services:
  database:
    container_name: mongo
    restart: always
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - delivery-mongo-db-data:/data/db
volumes:
  delivery-mongo-db-data:
