version: "3"

services:
  api:
    container_name: api
    restart: always
    build: ./adonis-backend
    ports:
      - "3333:3333"
    links:
      - mongo
      - redis
  job_feed:
    container_name: job_feed
    restart: always
    build: ./delivery-feed
    ports:
      - "3335:3335"
    links:
      - mongo
      - redis
  job_mail:
    container_name: job_mail
    restart: always
    build: ./delivery-jobs
    ports:
      - "3334:3334"
    links:
      - mongo
      - redis
  redis:
    container_name: redis
    restart: always
    build: ./redis
    ports:
      - "6379:6379"
  mongo:
    container_name: my-mongo
    restart: always
    build: ./mongo
    ports:
      - "27017:27017"
