version: "3"

services:
  job-feed:
    container_name: job-feed
    restart: always
    build: ./
    ports:
      - "3335:3335"
    env_file: .env
    volumes:
      - .:/usr/src/app
    links:
      - redis
    depends_on:
      - redis
  redis:
    container_name: redis
    restart: always
    build: ../redis
    ports:
      - "6379:6379"
