version: "3"

services:
  job_mail:
    container_name: job-mail
    restart: always
    build: ./
    ports:
      - "3334:3334"
    env_file: .env
    links:
      - redis
    depends_on:
      - redis
  redis:
    container_name: redis
    restart: always
    build: ../redis
    ports:
      - "6379:6379"
